language: php

php:
  - 7

script:
  - composer lint-yml
  - composer lint-twig
  - composer test
  - php bin/console doctrine:schema:validate --env=test

before_install:
  - npm install -g grunt-cli
  - sudo mysql -uroot -e "CREATE DATABASE emediatest;"
  - sudo mysql -uroot -e "CREATE USER 'emediatest'@'localhost' IDENTIFIED BY 'emediatest';"
  - sudo mysql -uroot -e "GRANT ALL ON emediatest.* TO 'emediatest'@'localhost'"

install:
  - composer install
  - composer install-assets
  - composer dump-translation
  - composer build-assets
  - composer create-test-schema
  - php bin/console doctrine:migrations:migrate --env=test -n
  - php bin/console doctrine:fixtures:load --no-interaction --env=test