<?php

namespace AppBundle\Repository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLatest($nth)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT v FROM AppBundle:Video v ORDER BY v.id DESC'
            )
            ->setMaxResults($nth)->getResult();
    }
}
