vich_uploader:
    db_driver: orm
    mappings:
        video_mapping:
            uri_prefix:         /video/
            upload_destination: '%kernel.root_dir%/../../videoapp-data/video/'
            namer: vich_uploader.namer_uniqid