vich_uploader:
    db_driver: orm
    mappings:
        video_mapping:
            uri_prefix:         /video/files
            upload_destination: '%kernel.root_dir%/../web/video/'
            namer: vich_uploader.namer_uniqid