encoder:
    resource: "@EncoderBundle/Resources/config/routing.yml"
    prefix:   /encoder

#app_user:
#    resource: "@AppUserBundle/Resources/config/routing.yml"
#    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
EndroidQrCodeBundle:
    resource: "@EndroidQrCodeBundle/Controller/"
    type:     annotation
    prefix:   /qrcode
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
app:
    resource: "@AppBundle/Resources/config/routing.yml"