home_index:
    path:     /home
    defaults: { _controller: "AppBundle:Home:index" }
    methods:  GET
home_version:
    path:     /version
    defaults: { _controller: "AppBundle:Home:version" }
    methods:  GET