video_stream:
    path:     /{id}
    defaults: { _controller: "AppBundle:Stream:stream" }
    methods:  GET
video_hls:
    path:     /{id}/hls/{file}
    defaults: { _controller: "AppBundle:Stream:Hls", file: null  }
    methods:  GET
#todo env var m3u8
video_hls_download_playlist_file:
  path:     /{id}/hls-download/{file}
  defaults: { _controller: "AppBundle:Stream:downloadHlsPlaylistFile" }
  methods:  GET

