stream_video:
    path:     /{id}/{frameSize}
    defaults: { _controller: "AppBundle:Stream:stream", frameSize: '720x480' }
    methods:  GET
stream_download_hls_file:
  path:     /{id}/hls/framesize/{frameSize}/file/{file}
  defaults: { _controller: "AppBundle:Stream:downloadHlsFile" }
  methods:  GET