video_download:
    path:     /{id}
    defaults: { _controller: "AppBundle:Stream:download" }
    methods:  GET
video_hls:
    path:     /{id}/hls/{file}
    defaults: { _controller: "AppBundle:Stream:Hls", file: null  }
    methods:  GET
video_hls_download_playlist_file:
  path:     /{id}/hls-download/framesize/{frameSize}/file/{file}
  defaults: { _controller: "AppBundle:Stream:downloadHlsPlaylistFile", frameSize: '1280x720'  }
  methods:  GET