user_index:
    path:     /
    defaults: { _controller: "AppBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}
    defaults: { _controller: "AppBundle:User:show" }
    methods:  GET