app_home:
    resource: '@AppBundle/Resources/config/routing/home.yml'
app_video:
    resource: '@AppBundle/Resources/config/routing/video.yml'
    prefix: video
app_user:
    resource: '@AppBundle/Resources/config/routing/user.yml'
    prefix: user