app_home:
    resource: '@AppBundle/Resources/config/routing/home.yml'
app_video:
    resource: '@AppBundle/Resources/config/routing/video.yml'
    prefix: video
app_user:
    resource: '@AppBundle/Resources/config/routing/user.yml'
    prefix: user
app_tag:
        resource: "@AppBundle/Resources/config/routing/tag.yml"
        prefix:   /tag
app_stream:
        resource: "@AppBundle/Resources/config/routing/stream.yml"
        prefix:   /stream
app_lti:
        resource: "@AppBundle/Resources/config/routing/lti.yml"
        prefix:   /lti
