AppBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 100
        lastName:
            type: string
            length: 100
    oneToMany:
        videos:
          targetEntity: AppBundle\Entity\Video
          mappedBy: creator