AppBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO