AppBundle\Entity\Video:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\VideoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: string
            length: 255
        videoName:
            type: string
            length: 255
            nullable: true

    lifecycleCallbacks: {  }
