AppBundle\Entity\Video:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\VideoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: string
            length: 255
        videoName:
            type: string
            length: 255
            nullable: true
    manyToMany:
      tags:
        targetEntity: AppBundle\Entity\Tag
        inversedBy: videos
        nullable: false
        joinTable:
          name: videos_tags
          joinColumns:
            video_id:
              referencedColumnName: id
          inverseJoinColumns:
            tag_id:
              referencedColumnName: id
    manyToOne:
        creator:
          targetEntity: AppBundle\Entity\User
          inversedBy: videos
          joinColumn:
            name: user_id
            referencedColumnName: id
            nullable: false
    lifecycleCallbacks: {  }
